config/routes.rb
Rails.application.routes.draw do
  resources :admin_posts

  resources :posts
  get 'admin_users' => 'admin_users#index' 
  get 'admin_users/show/:id' => 'admin_users#show'
  get 'admin_users/apis' => 'admin_users#apis'

  resources :posts do
    collection do
      post 'like'
      post 'comment'
    end
  end

  root 'posts#index'

end

app/models/admin_post.rb
class AdminPost < ActiveRecord::Base
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :posts
end

app/models/comment_like.rb
class CommentLike < ActiveRecord::Base
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :likes
  mount_uploader :image, ImageUploader
end

app/models/sabae_p.rb
class SabaeP < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
end

app/controllers/admin_posts_controller.rb
class AdminPostsController < ApplicationController
  before_action :set_admin_post, only: [:show, :edit, :update, :destroy]

  # GET /admin_posts
  # GET /admin_posts.json
  def index
    @admin_posts = AdminPost.all
  end

  # GET /admin_posts/1
  # GET /admin_posts/1.json
  def show
  end

  # GET /admin_posts/new
  def new
    @admin_post = AdminPost.new
  end

  # GET /admin_posts/1/edit
  def edit
  end

  # POST /admin_posts
  # POST /admin_posts.json
  def create
    @admin_post = AdminPost.new(admin_post_params)

    respond_to do |format|
      if @admin_post.save
        format.html { redirect_to @admin_post, notice: 'Admin post was successfully created.' }
        format.json { render :show, status: :created, location: @admin_post }
      else
        format.html { render :new }
        format.json { render json: @admin_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin_posts/1
  # PATCH/PUT /admin_posts/1.json
  def update
    respond_to do |format|
      if @admin_post.update(admin_post_params)
        format.html { redirect_to @admin_post, notice: 'Admin post was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_post }
      else
        format.html { render :edit }
        format.json { render json: @admin_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_posts/1
  # DELETE /admin_posts/1.json
  def destroy
    @admin_post.destroy
    respond_to do |format|
      format.html { redirect_to admin_posts_url, notice: 'Admin post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_post
      @admin_post = AdminPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_post_params
      params.require(:admin_post).permit(:title, :content, :image, :user_id, :deadline, :valiable)
    end
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
	layout 'admin', :only => [:index, :show, :apis]
	def index
		session[:admin_user] = 1
		if session[:admin_user] != nil
			# search post by encoded city_name but data is 
			# @likes = Post.joins("LEFT OUTER JOIN `likes` ON `likes`.`post_id` = `posts`.`id`")
			@posts = Post.all
			
			@posts.each do |post|
				str = post.id.to_s
				@li = ActiveRecord::Base.connection.select("SELECT likes.* FROM likes LEFT OUTER JOIN posts ON likes.post_id = posts.id where post_id = " + str)
				@comment = ActiveRecord::Base.connection.select("SELECT comments.* FROM comments LEFT OUTER JOIN posts ON comments.post_id = posts.id where post_id = " + str)
	
				post.image = get_size(@li)
				post.city_name = get_size(@comment)
			end
		else 
		
		end
	end

	def show
		@post = Post.find_by(:id => params[:id])
  category = [1,3,5,7]
    current_quantity = [1000,5000,3000,8000]

    @graph = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(text: 'ItemXXXの在庫の推移')
      f.xAxis(categories: category)
      f.series(name: '在庫数', data: current_quantity)
    end


		@chart = LazyHighCharts::HighChart.new('pie') do |f|
		f.chart({
			 defaultSeriesType: 'pie',
			 margin: [50, 200, 60, 170],
			 plotBackgroundColor: nil,
			 plotBorderWidth: nil,
			 plotShadow: false})
		f.plotOptions({
			pie: {
				allowPointSelect: true,
				cursor: 'pointer',
				dataLabels: {
					enabled: false
				},
				showInLegend: true
			}
		})
		f.series({
		  type: 'pie',
		  name: 'hoge',
		  data: [
			['10 ~ 20代', 10.0],
			['20 ~ 30代', 15.0],
			['30 ~ 40代', 20.0],
			['40 ~ 50代', 15.0]
		  ]
		})
	  end

	end

	def apis

	  xAxis_categories = ['平成20年', '平成21年', '平成22年', '平成23年', '平成24年']
      tickInterval     = 2
      data             = [691, 628, 693, 643, 659]
	  data2			   = [556, 599, 618, 641, 587]
      @graph_data = LazyHighCharts::HighChart.new('graph') do |f|
        f.title(text: '人口動態(自然増減)')
        f.xAxis(categories: xAxis_categories, tickInterval: tickInterval)
        f.series(name: '出生数', data: data, type: 'spline')
 		f.series(name: '死亡数', data: data2, type: 'spline')
      end





	end	

	def login 
		
	end
	private
		def get_size(array)
			num = 0;
			array.each do |post|
				num += 1;
			end
			return num
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
# coding: utf-8
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @user = User.find(1)
    @posts = Post.all.order(created_at: :desc)
    session[:user_id] = @user.id
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  def like
    post_id = 3# params[:post_id]
    if Like.where(post_id: post_id, user_id: session[:user_id]).first
      @done = true
    else
      like = Like.new
      like.user_id = session[:user_id]
      like.post_id = post_id
      like.valiable = true
      like.save
      @done = false
    end
    redirect_to '/posts'
  end

  def comment
    post_id = 3 # params[:post_id]
    comment = Comment.new
    comment.content = "これすごく良くわかります。よろしくお願い致します。"# params[:comment]
    comment.user_id = session[:user_id]
    comment.post_id = post_id
    comment.save
    redirect_to '/posts'
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to '/posts', notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :image, :user_id, :x_locate, :y_locate, :valiable)
    end
end

app/helpers/admin_posts_helper.rb
module AdminPostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin_posts/_form.html.erb
<%= form_for(@admin_post) do |f| %>
  <% if @admin_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_post.errors.count, "error") %> prohibited this admin_post from being saved:</h2>

      <ul>
      <% @admin_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_area :image %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :valiable %><br>
    <%= f.check_box :valiable %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin_posts/edit.html.erb
<h1>Editing admin_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_post %> |
<%= link_to 'Back', admin_posts_path %>

app/views/admin_posts/index.html.erb
<h1>Listing admin_posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Image</th>
      <th>User</th>
      <th>Deadline</th>
      <th>Valiable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_posts.each do |admin_post| %>
      <tr>
        <td><%= admin_post.title %></td>
        <td><%= admin_post.content %></td>
        <td><%= admin_post.image %></td>
        <td><%= admin_post.user_id %></td>
        <td><%= admin_post.deadline %></td>
        <td><%= admin_post.valiable %></td>
        <td><%= link_to 'Show', admin_post %></td>
        <td><%= link_to 'Edit', edit_admin_post_path(admin_post) %></td>
        <td><%= link_to 'Destroy', admin_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin post', new_admin_post_path %>

app/views/admin_posts/new.html.erb
<h1>New admin_post</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_posts_path %>

app/views/admin_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @admin_post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @admin_post.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= @admin_post.image %>
</p>

<p>
  <strong>User:</strong>
  <%= @admin_post.user_id %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @admin_post.deadline %>
</p>

<p>
  <strong>Valiable:</strong>
  <%= @admin_post.valiable %>
</p>

<%= link_to 'Edit', edit_admin_post_path(@admin_post) %> |
<%= link_to 'Back', admin_posts_path %>

app/views/admin_users/apis.html.erb
<div class="large-8 medium-8 medium-potrait-8 columns mo-animate" data-animate="fadeInDown" style="padding-left: 80px;">
	<%= high_chart("hoge", @graph_data) %>

</div>

app/views/admin_users/index.html.erb
            <div class="large-8 medium-8 medium-potrait-8 columns mo-animate" data-animate="fadeInDown" style="padding-left: 80px">
               <table class="table blue">
                  <thead>
                     <tr>
                        <th class="align-center table-width5">#</th>
                        <th class="table-width30">Title</th>
                        <th class="table-width30">内容</th>
                        <th class="table-width30">いいね数</th>
                        <th class="table-width30">コメント数</th>
                     </tr>
                  </thead>
                  <tbody>
					<% @posts.each do |post| 
						link = 'show/' + post.id.to_s						
%>
                     <tr>
                        <td class="align-center"><%= post.id %></td>
                        <td><a href= <%= link %>><%= post.title %></a></td>
						<td><%= truncate(post.content, length: 15)  %></td>
                        <td><%= post.image %></td>
                        <td><%= post.city_name %></td>
                     </tr>
					<% end %>
                  </tbody>
               </table>    
            </div>

app/views/admin_users/login.html.erb
<h2> new admin </h2>

app/views/admin_users/show.html.erb
      <div class="large-8 medium-8 medium-potrait-8 columns mo-animate">
        <div style="whight:40%">
           <h3 class="gap" data-top="20" data-bottom="12"><%= @post.title %></h3>
        </div>

        <div style="margin: auto auto 0.5em;">
           <p style="margin: auto auto 0.5em;"><%= @post.content %></p>
           <p style="text-align: right;margin: auto auto 0.5em;">投稿者:</p>
           <p style="text-align: right;margin: auto auto 0.5em;">投稿日:</p>
        </div>

        <div class="row" >
          <div class="large-6 columns mo-animate" data-animate="fadeInLeft">
                <div id="top-tab">
                  <!-- tab list -->
                  <ul class="resp-tabs-list" style="float: left">
                     <li style="float: left"><i class="icon-briefcase"></i> Sample 1</li>
                     <li style="float: left"><i class="icon-calculator"></i> Sample 2</li>
                  </ul>

                  <!-- tab container -->
                  <div class="resp-tabs-container">
                     <div>
                        <p>
                           <%= high_chart("hoge", @graph) %>
                        </p>
                     </div>
					 <div>
                        <p>
                        </p>
                     </div>

                  </div>
                  <!-- end tab container -->
               </div>
          </div>
        <div class="large-6 columns mo-animate" data-animate="fadeInLeft">
                <div id="top-tab">
                  <!-- tab list -->
                  <ul class="resp-tabs-list" style="float:left">
                     <li style="float:left"><i class="icon-briefcase"></i> Sample 1</li>
                     <li style="float:left"><i class="icon-calculator"></i> Sample 2</li>
                  </ul>

                  <!-- tab container -->
                  <div class="resp-tabs-container">
                     <div>
                        <p>
                           <%= high_chart("hogea", @graph) %>
                        </p>
                     </div>

                  </div>
                  <!-- end tab container -->
               </div>
          </div>
		  </div>

           <div class="blog-author mo-animate" data-animate="fadeInDown">
              <h5>コメント</h5>

              <h6></h6>
              <p class="text-overflow">
              </p>

              <h6></h6>
              <p class="text-overflow">
                 Everything you're seeing here is pulled through dynamically from the WordPress admin panel. Simply go to your user profile, fille out the URLs to your social media profiles, fill in the biographical info, and you're good to go!
              </p>

           </div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Getwill</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>




<div class="rowa">
			<div class="large-3 medium-3 columns mo-animate" data-animate="fadeInLeft">
               <div id="left-tab">
                  <!-- tab list -->
                  <ul class="resp-tabs-list">
                     <a href="/admin_users"><li id ="posts">Posts</li></a>
                     <li><i class="icon-calculator"></i>Sample</li>
                     <a href="/admin_users/apis"><li><i class="icon-stickynote"></i> Sample 3</li></a>
                  </ul>

               </div>
            </div>
</div>
<%= yield %>
</body>
	<script>
	</script>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">

   <title>GetWill</title>
   <%= include_gon %>
   
   <%= stylesheet_link_tag 'application' %>
      
   <!-- Favicon -->
   <!-- "img/favicon.ico" rel="shortcut icon" / -->

   <!-- Google Webfont -->
   <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet'>
   <link href='http://fonts.googleapis.com/css?family=Noto+Serif:400,700' rel='stylesheet' type='text/css'>
   <link href='http://fonts.googleapis.com/css?family=Yellowtail' rel='stylesheet' type='text/css'>
   <link href='http://fonts.googleapis.com/css?family=Goudy+Bookletter+1911' rel='stylesheet'>
   <%= javascript_include_tag 'application' %>
</head>

<body>

	<%= yield %>

	<script type="text/javascript">
		jQuery(document).ready(function($){
		});
	</script>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <ul class="comment-form"> 
    <li class="subj-ico"><%= f.text_field :title, :class => "form-control", :placeholder => "タイトル" %></li>
    <li><%= f.text_area :content, :size => "20x10", :class => "form-control", :placeholder => "内容" %></li>
    <li>画像ファイル：<%= f.file_field :image, :class => "form-control" %></li>
    <li><%= button_tag "送信", :class => "actions button yellow" %>
        <%= button_tag "リセット", :class => "actions button gray", :type => "reset" %></li>
  </ul>

<!--
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

-->
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div id="mo-wrapper">
  <section id="panel">
    <div class="row">
      <form action="./" class="mo-animate" data-animate="fadeInDown">
        <div class="row">
          <div class="form-group large-3 columns">
          </div>
          <div class="form-group large-6 columns">
            <input type="text" class="form-control input-lg" id="name" placeholder="Search Word">
          </div>
          <div class="form-inline large-1 columns remember">
            <button type="submit" class="button small blue">検索<i class="icon-search"></i></button>
          </div>
        </div>
      </form>
    </div>
  </section>

  <header>
    <div class="row">
      <div class="large-12 columns">
        <div id="toggle-panel">
          <a href="#" id="toggle"><i class="icon-search"></i></a> <!-- 検索はここにかく -->
        </div>

        <div id="logo">
          <a href="/">
            <h2 class="mega">GetWill</h2>
          </a>
        </div>

        <nav id="mo-menu">
          <ul class="menu sm">
            <li><a href="/posts">タイムライン</a></li>
            <li><a href="/posts/new">投稿</a></li>
            <li><a href="#">マイページ</a></li>
            <li><a href="#">Q＆A</a></li>
          </ul>
        </nav>
      </div>
    </div>
  </header>

  <section class="mo-content"
    <div class="row">
      <div class="large-12 columns">
        <ul class="timeline">
          <% @posts.each do |post| %>
            <li id ="tid<%= post.id %>" class="mo-animate posts" data-animate="fadeInDown">
              <div class="timeline-container">
                <div class="feature-left">
                  <h5 class="gap" data-top="20" data-bottom="12"><%= post.title%></h5>
                  <p><%= post.content %></p>
                  <% if post.image? %>
                    <a target="_blank" href="<%= post.image.url %>" ><%= image_tag post.image.url, :class =>'thumbnail' %></a>
                  <% else %>
                    <%= image_tag 'noimage.gif' %>
                  <% end %>
                  <% post_datetime = post.created_at.to_s(:datetime).split(" ") %>
                  <div class ="auther">
                    <%= post_datetime[0].split("-").join("/") + " " %>
                    <%= post_datetime[1] %><br>
                    <span>投稿者: 利他 理太</span>
                  </div>
                </div>
              </div>
              <div class="timeline-footer">
                <div class="footer-content">
                  <ul class="inline-list">
                    <li><a class="btn-comment" id ="<%= post.id %>"><i class="icon-comment"></i> 25</a></li>
                    <li><a class="like-btn" id="like-btn<%= post.id %>"><i class="icon-fblike"></i> 100</a></li>
                  </ul>
                </div>
              </div>
              <!-- コメント -->
              <div class="timeline-container comments" id ="tc<%= post.id %>" >
                <% if !@comments.nil? %>
                  <% @comments.each do |comment| %>
                    <div class="feature-left" id="cid<%= comment.id %>">
                      <h5 class="gap" data-top="20" data-bottom="12">私も賛成ですー</h5>
                      <p>　私も賛成ですー。</p>
                      <div class ="auther">2014/11/12 23:43<br>投稿者: 山田花子</div>
                    </div>
                  <% end %>
                <% end  %>
                <form action="./" class="new_post" enctype="multipart/form-data" id="new_post" method="post">
                  <ul class="comment-form">･
                    <li class="subj-ico"><input class="form-control" id="post_title" name="post[title]" placeholder="タイトル" type="text" /></li>
                    <li><textarea class="form-control" cols="20" id="post_content" name="post[content]" placeholder="内容" rows="5"></textarea></li>
                    <li><button class="actions button yellow" name="button" type="submit">送信</button>
                      <button class="actions button gray" name="button" type="reset">リセット</button></li>
                  </ul>
                </form>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </section>


  <footer>
    <div id="copyright">
      <div class="row">
        <div class="large-12 columns text-center">
          Created with  by ちーむりたりた. &copy; 2014 all rights reserved
        </div>
      </div>
    </div>
  </footer>


</div>

<!-- javascript here -->
<script type="text/javascript">
  jQuery(document).ready(function(){
    $(".comments").hide();
        $(".btn-comment").click(function(){
          var id = $(this).attr('id');
          $("[id='tc"+id+"']").slideToggle();
        });

  });
</script>

app/views/posts/new.html.erb
  <div id="mo-wrapper">
    <section id="panel">
     <div class="row">
       <form action="#" class="mo-animate" data-animate="fadeInDown">
        <div class="row">
         <div class="form-group large-3 columns">
         </div>
         <div class="form-group large-6 columns">
          <input type="text" class="form-control input-lg" id="name" placeholder="Search Word">
        </div>
        <div class="form-inline large-1 columns remember">
         <button type="submit" class="button small blue">検索<i class="icon-search"></i></button>
       </div>
     </div>
   </form>
 </div>
</section>

<header>
  <div class="row">
    <div class="large-12 columns">
     <div id="toggle-panel">
      <a href="#" id="toggle"><i class="icon-search"></i></a> <!-- 検索はここにかく -->
    </div>

    <div id="logo">
      <a href="/">
       <h2 class="mega">GetWill<span></h2>
     </a>
   </div>

   <nav id="mo-menu">
    <ul class="menu sm">
      <li><a href="/posts">タイムライン</a></li>
      <li><a href="/posts/new">投稿</a></li>
      <li><a href="#">マイページ</a></li>
      <li><a href="#">Q＆A</a></li>
    </ul>
  </nav>

</div>
</div>
</header>



<section class="mo-content">
	<div class="row">
		<div class="large-8 columns">
            <div id="comment" class="triggerAnimation animated" data-animate="fadeInDown">
                  <h4 class="mo-animate" data-animate="fadeInLeft">意見を送る</h4> 
                  <%= render 'form' %>
            </div>
		</div>				
	</div>   
</section>

  <footer>
        <div id="copyright">
            <div class="row">
               <div class="large-12 columns text-center">
                  Created with  by ちーむりたりた. &copy; 2014 all rights reserved
               </div>
            </div>
         </div>
 </footer>

</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= @post.image %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<p>
  <strong>X locate:</strong>
  <%= @post.x_locate %>
</p>

<p>
  <strong>Y locate:</strong>
  <%= @post.y_locate %>
</p>

<p>
  <strong>Valiable:</strong>
  <%= @post.valiable %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>